In [1]:
import numpy as np


In [7]:
#lists
aList = [0,1,2,3,4,5]
print(aList)
print(type(aList))
listList = [3,['4','5'],5.5,[4,5,6]]
print(listList)
print(type(listList))
print(listList[3])

[0, 1, 2, 3, 4, 5]
<class 'list'>
[3, ['4', '5'], 5.5, [4, 5, 6]]
<class 'list'>
[4, 5, 6]


In [ ]:
# matemathical operation on lists are possible
aList = [0,1,2,3,4,5]
bList = ['0','2','3','4','5']

print(aList + bList)
print(aList * 3) #it will repeate the entire aList 3 times 


[0, 1, 2, 3, 4, 5, '0', '2', '3', '4', '5']
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


In [15]:
#numpy arrays
aList_np = np.array(aList)
print(type(aList_np))
print(aList_np)
print(aList_np * 3)
print(aList_np + aList_np) # here is the difference between lists and np arrays behavior. Every np.array item is affected by multiplied/devided/substracted/added

<class 'numpy.ndarray'>
[0 1 2 3 4 5]
[ 0  3  6  9 12 15]
[ 0  2  4  6  8 10]


In [16]:
#enumerates returns 2 elements in list, index and item

s = 'mike'
for i,item in enumerate(s):
    print(i, item)

0 m
1 i
2 k
3 e
